version: 2
updates:
  - package-ecosystem: nuget
    directory: "/backend"
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dotnet
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directories:
      - "/web"
      - "/admin"
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 8
    labels:
      - dependencies
      - frontend
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    labels:
      - dependencies
      - ci
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directories:
      - /backend/Api
      - /backend/Ingestor
      - /web
      - /admin
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    labels:
      - dependencies
      - docker
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker-compose
    directory: "/"
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    labels:
      - dependencies
      - docker
    ignore:
      - dependency-name: "ghcr.io/ilyanfraimbault/truemain-*"
    groups:
      compose-images:
        patterns:
          - "*"
