using Core.Lol.Spells;
using Data.Entities;

namespace Ingestor.Processes.Components.PatternAggregation;

public sealed class ChampionPatternAggregateBuilder(
    IItemMetadataProvider itemMetadataProvider)
{
    internal async Task<ChampionPatternAggregationResult> BuildAggregatesAsync(
        IReadOnlyCollection<AggregateSourceRow> sourceRows,
        DateTime aggregatedAtUtc,
        CancellationToken ct)
    {
        var expandedRows = await ExpandSourceRowsAsync(sourceRows, ct);

        var scopes = BuildScopes(expandedRows, aggregatedAtUtc);
        var patterns = BuildPatternIntents(expandedRows, scopes);

        return new ChampionPatternAggregationResult
        {
            SourceRowCount = sourceRows.Count,
            Scopes = scopes,
            Patterns = patterns
        };
    }

    private static List<PatternIntent> BuildPatternIntents(
        IReadOnlyList<ExpandedSourceRow> expandedRows,
        IReadOnlyList<ChampionAggregateScope> scopes)
    {
        // Resolve scope IDs by their natural key — the scopes list was just
        // generated by BuildScopes, so its Guids are in-memory only and the
        // persister will use them when it inserts. Pattern intents have to
        // reference the same scope IDs to satisfy the new FK once both
        // tables hit Postgres.
        var scopeIdByKey = scopes.ToDictionary(
            scope => new AggregateScopeKeyWithAccount(
                scope.RiotAccountId,
                scope.ChampionId,
                scope.GameVersion,
                scope.PlatformId,
                scope.QueueId,
                scope.Position),
            scope => scope.Id);

        return expandedRows
            .GroupBy(row => new
            {
                ScopeKey = new AggregateScopeKeyWithAccount(
                    row.RiotAccountId,
                    row.ChampionId,
                    row.GameVersion,
                    row.PlatformId,
                    row.QueueId,
                    row.Position),
                Build = new BuildDimensionContent(
                    row.BootsItemId,
                    row.BuildItem0, row.BuildItem1, row.BuildItem2, row.BuildItem3,
                    row.BuildItem4, row.BuildItem5, row.BuildItem6),
                RunePage = new RunePageDimensionContent(
                    row.PrimaryStyleId,
                    row.PrimaryKeystoneId,
                    row.PrimaryPerk1Id,
                    row.PrimaryPerk2Id,
                    row.PrimaryPerk3Id,
                    row.SubStyleId,
                    row.SecondaryPerk1Id,
                    row.SecondaryPerk2Id,
                    row.PerksOffense,
                    row.PerksFlex,
                    row.PerksDefense),
                row.SkillOrderKey,
                SpellPair = new SpellPairDimensionContent(row.SummonerSpell1Id, row.SummonerSpell2Id),
                row.StarterItemsKey
            })
            .Where(group => scopeIdByKey.ContainsKey(group.Key.ScopeKey))
            .Select(group => new PatternIntent(
                ScopeId: scopeIdByKey[group.Key.ScopeKey],
                Build: group.Key.Build,
                RunePage: group.Key.RunePage,
                SkillOrderKey: group.Key.SkillOrderKey,
                SpellPair: group.Key.SpellPair,
                StarterItemsKey: group.Key.StarterItemsKey,
                StarterItems: group.First().StarterItems,
                Games: group.Count(),
                Wins: group.Count(row => row.Win)))
            .ToList();
    }

    private static List<ChampionAggregateScope> BuildScopes(
        IReadOnlyList<ExpandedSourceRow> expandedRows,
        DateTime aggregatedAtUtc)
        => expandedRows
            .GroupBy(row => new AggregateScopeKeyWithAccount(
                row.RiotAccountId,
                row.ChampionId,
                row.GameVersion,
                row.PlatformId,
                row.QueueId,
                row.Position))
            .OrderBy(group => group.Key.RiotAccountId)
            .ThenBy(group => group.Key.ChampionId)
            .ThenBy(group => group.Key.GameVersion)
            .ThenBy(group => group.Key.PlatformId)
            .ThenBy(group => group.Key.Position)
            .Select(group => BuildScope(group, aggregatedAtUtc))
            .ToList();

    private static ChampionAggregateScope BuildScope(
        IGrouping<AggregateScopeKeyWithAccount, ExpandedSourceRow> group,
        DateTime aggregatedAtUtc)
    {
        var rows = group.ToList();

        return new ChampionAggregateScope
        {
            Id = Guid.NewGuid(),
            RiotAccountId = group.Key.RiotAccountId,
            ChampionId = group.Key.ChampionId,
            GameVersion = group.Key.GameVersion,
            PlatformId = group.Key.PlatformId,
            QueueId = group.Key.QueueId,
            Position = group.Key.Position,
            Games = rows.Count,
            Wins = rows.Count(row => row.Win),
            LastGameStartTimeUtc = rows.Max(row => row.GameStartTimeUtc),
            AggregatedAtUtc = aggregatedAtUtc
        };
    }

    private async Task<List<ExpandedSourceRow>> ExpandSourceRowsAsync(
        IReadOnlyCollection<AggregateSourceRow> sourceRows,
        CancellationToken ct)
    {
        var expandedRows = new List<ExpandedSourceRow>(sourceRows.Count);

        foreach (var row in sourceRows)
        {
            var itemMetadata = await itemMetadataProvider.GetItemsAsync(row.GameVersion, ct);
            int[] finalItems = [row.Item0, row.Item1, row.Item2, row.Item3, row.Item4, row.Item5, row.Item6];
            var starterAnalysis = StarterItemAnalyzer.Analyze(row.ItemEvents, finalItems, itemMetadata);

            var (spell1Id, spell2Id) = new SummonerSpellPair(row.Summoner1Id, row.Summoner2Id).Canonical();
            var skillOrderKey = SkillOrderBuilder.Build(row.SkillEvents);
            var buildItems = FinalBuildResolver.Resolve(row.ItemEvents, finalItems, starterAnalysis.Items, itemMetadata);
            var bootsItemId = BootsResolver.Resolve(row.ItemEvents, finalItems, starterAnalysis.Items, itemMetadata);
            var slots = PadBuildItems(buildItems);

            expandedRows.Add(new ExpandedSourceRow(
                row.RiotAccountId,
                row.ChampionId,
                row.GameVersion,
                row.PlatformId,
                row.QueueId,
                row.Position ?? string.Empty,
                row.PrimaryStyleId,
                row.SubStyleId,
                row.PerksOffense,
                row.PerksFlex,
                row.PerksDefense,
                row.PrimaryKeystoneId,
                row.PrimaryPerk1Id,
                row.PrimaryPerk2Id,
                row.PrimaryPerk3Id,
                row.SecondaryPerk1Id,
                row.SecondaryPerk2Id,
                spell1Id,
                spell2Id,
                skillOrderKey,
                starterAnalysis.Items,
                bootsItemId,
                slots[0],
                slots[1],
                slots[2],
                slots[3],
                slots[4],
                slots[5],
                slots[6],
                row.Win,
                row.GameStartTimeUtc));
        }

        return expandedRows;
    }

    private static int[] PadBuildItems(IReadOnlyList<int> normalizedItems)
    {
        var padded = new int[7];
        for (var i = 0; i < normalizedItems.Count && i < padded.Length; i++)
        {
            padded[i] = normalizedItems[i];
        }

        return padded;
    }
}

internal sealed record AggregateScopeKeyWithAccount(
    Guid RiotAccountId,
    int ChampionId,
    string GameVersion,
    string PlatformId,
    int QueueId,
    string Position);
