// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Data;
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(TrueMainDbContext))]
    [Migration("20260315222639_RestrictProcessRunErrorLength")]
    partial class RestrictProcessRunErrorLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.MainCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<long>("ChampionPoints")
                        .HasColumnType("bigint");

                    b.Property<int>("ChampionRankInMasteryTop")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastPlayTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ScoredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("PlatformId", "Puuid", "ChampionId")
                        .IsUnique();

                    b.HasIndex("PlatformId", "Status", "Score");

                    b.ToTable("main_candidates", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MainChampionStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionMatches")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOtp")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<double>("PlayRate")
                        .HasColumnType("double precision");

                    b.Property<List<PositionStat>>("PositionBreakdown")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId", "Puuid");

                    b.HasIndex("PlatformId", "Puuid", "ChampionId")
                        .IsUnique();

                    b.ToTable("main_champion_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GameDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("GameStartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<bool>("TimelineIngested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("TimelineIngested")
                        .HasDatabaseName("IX_matches_timeline_ingested");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<string>("IndividualPosition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Item0")
                        .HasColumnType("integer");

                    b.Property<int>("Item1")
                        .HasColumnType("integer");

                    b.Property<int>("Item2")
                        .HasColumnType("integer");

                    b.Property<int>("Item3")
                        .HasColumnType("integer");

                    b.Property<int>("Item4")
                        .HasColumnType("integer");

                    b.Property<int>("Item5")
                        .HasColumnType("integer");

                    b.Property<int>("Item6")
                        .HasColumnType("integer");

                    b.Property<List<ItemEvent>>("ItemEvents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("NeutralMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PerksDefense")
                        .HasColumnType("integer");

                    b.Property<int>("PerksFlex")
                        .HasColumnType("integer");

                    b.Property<int>("PerksOffense")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryStyleId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<List<SkillEvent>>("SkillEvents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SubStyleId")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner2Id")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SummonerName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamPosition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("TrinketItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("match_participants", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ParticipantPerkSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PerkSelectionCatalogId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerkSelectionCatalogId");

                    b.HasIndex("MatchId", "ParticipantId", "PerkSelectionCatalogId")
                        .IsUnique();

                    b.ToTable("participant_perk_selections", (string)null);
                });

            modelBuilder.Entity("Data.Entities.PerkSelectionCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PerkId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("StyleDescription")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StyleId", "SelectionIndex", "PerkId", "StyleDescription")
                        .IsUnique();

                    b.ToTable("perk_selection_catalog", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ProcessRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Summary")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ProcessName", "StartedAtUtc");

                    b.ToTable("process_runs", (string)null);
                });

            modelBuilder.Entity("Data.Entities.RiotAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastMainCalcAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMatchIngestAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastProfileSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MatchIngestClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchIngestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SummonerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SummonerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("TagLine")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.HasIndex("GameName", "TagLine", "PlatformId")
                        .IsUnique();

                    b.HasIndex("MatchIngestStatus", "MatchIngestClaimedAtUtc", "LastMatchIngestAtUtc")
                        .HasDatabaseName("IX_riot_accounts_ingest_claim_lease");

                    b.ToTable("riot_accounts", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MatchParticipant", b =>
                {
                    b.HasOne("Data.Entities.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Data.Entities.ParticipantPerkSelection", b =>
                {
                    b.HasOne("Data.Entities.PerkSelectionCatalog", null)
                        .WithMany()
                        .HasForeignKey("PerkSelectionCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.RiotAccount", b =>
                {
                    b.HasOne("Data.Entities.Persona", "Persona")
                        .WithMany("RiotAccounts")
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Data.Entities.Match", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Data.Entities.Persona", b =>
                {
                    b.Navigation("RiotAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
