// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Data;
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(TrueMainDbContext))]
    partial class TrueMainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.ChampionAggregatePattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunePageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellPairId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StarterItemsId")
                        .HasColumnType("uuid");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("RunePageId");

                    b.HasIndex("SkillOrderId");

                    b.HasIndex("SpellPairId");

                    b.HasIndex("StarterItemsId");

                    b.HasIndex("ScopeId", "BuildId");

                    b.HasIndex("ScopeId", "RunePageId");

                    b.HasIndex("ScopeId", "SkillOrderId");

                    b.HasIndex("ScopeId", "SpellPairId");

                    b.HasIndex("ScopeId", "StarterItemsId");

                    b.HasIndex("ScopeId", "BuildId", "RunePageId", "SkillOrderId", "SpellPairId", "StarterItemsId")
                        .IsUnique();

                    b.ToTable("champion_aggregate_patterns", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionAggregateScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AggregatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Assists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("EloBracket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("elo_bracket");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastGameStartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId", "GameVersion", "PlatformId", "QueueId");

                    b.HasIndex("RiotAccountId", "ChampionId", "GameVersion", "PlatformId", "Position");

                    b.HasIndex("ChampionId", "GameVersion", "PlatformId", "QueueId", "Position", "EloBracket")
                        .HasDatabaseName("IX_champion_aggregate_scopes_ChampionId_GameVersion_PlatformI~1");

                    b.HasIndex("RiotAccountId", "ChampionId", "GameVersion", "PlatformId", "QueueId", "Position", "EloBracket")
                        .IsUnique()
                        .HasDatabaseName("IX_champion_aggregate_scopes_RiotAccountId_ChampionId_GameVer~1");

                    b.ToTable("champion_aggregate_scopes", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionDimBuild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BootsItemId")
                        .HasColumnType("integer");

                    b.Property<int>("BuildItem0")
                        .HasColumnType("integer");

                    b.Property<int>("BuildItem1")
                        .HasColumnType("integer");

                    b.Property<int>("BuildItem2")
                        .HasColumnType("integer");

                    b.Property<int>("BuildItem3")
                        .HasColumnType("integer");

                    b.Property<int>("BuildItem4")
                        .HasColumnType("integer");

                    b.Property<int>("BuildItem5")
                        .HasColumnType("integer");

                    b.Property<int>("BuildItem6")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BootsItemId", "BuildItem0", "BuildItem1", "BuildItem2", "BuildItem3", "BuildItem4", "BuildItem5", "BuildItem6")
                        .IsUnique();

                    b.ToTable("champion_dim_builds", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionDimRunePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PrimaryKeystoneId")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryPerk1Id")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryPerk2Id")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryPerk3Id")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryStyleId")
                        .HasColumnType("integer");

                    b.Property<int>("SecondaryPerk1Id")
                        .HasColumnType("integer");

                    b.Property<int>("SecondaryPerk2Id")
                        .HasColumnType("integer");

                    b.Property<int>("SecondaryStyleId")
                        .HasColumnType("integer");

                    b.Property<int>("StatDefense")
                        .HasColumnType("integer");

                    b.Property<int>("StatFlex")
                        .HasColumnType("integer");

                    b.Property<int>("StatOffense")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryStyleId", "PrimaryKeystoneId", "PrimaryPerk1Id", "PrimaryPerk2Id", "PrimaryPerk3Id", "SecondaryStyleId", "SecondaryPerk1Id", "SecondaryPerk2Id", "StatOffense", "StatFlex", "StatDefense")
                        .IsUnique();

                    b.ToTable("champion_dim_rune_pages", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionDimSkillOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SkillOrderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SkillOrderKey")
                        .IsUnique();

                    b.ToTable("champion_dim_skill_orders", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionDimSpellPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Spell1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Spell2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Spell1Id", "Spell2Id")
                        .IsUnique();

                    b.ToTable("champion_dim_spell_pairs", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionDimStarterItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("StarterItems")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StarterItemsKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("StarterItemsKey")
                        .IsUnique();

                    b.ToTable("champion_dim_starter_items", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionMatchupStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AggregatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("EloBracket")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("")
                        .HasColumnName("elo_bracket");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("OpponentChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TeamPosition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId", "TeamPosition", "OpponentChampionId", "Patch", "EloBracket")
                        .IsUnique();

                    b.ToTable("champion_matchup_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionPowerspikeCurveStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AggregatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("EloBracket")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("")
                        .HasColumnName("elo_bracket");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalMinute")
                        .HasColumnType("integer");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TeamPosition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("TotalDamageDiff")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalGoldDiff")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId", "TeamPosition", "Patch", "EloBracket", "IntervalMinute")
                        .IsUnique();

                    b.ToTable("champion_powerspike_curve_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionPowerspikeEventStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AggregatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("EloBracket")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("")
                        .HasColumnName("elo_bracket");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("RefId")
                        .HasColumnType("integer");

                    b.Property<double>("SumMinute")
                        .HasColumnType("double precision");

                    b.Property<double>("SumSpike")
                        .HasColumnType("double precision");

                    b.Property<string>("TeamPosition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId", "TeamPosition", "Patch", "EloBracket", "EventType", "RefId")
                        .IsUnique();

                    b.ToTable("champion_powerspike_event_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionTimelineLeadStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AggregatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("EloBracket")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("")
                        .HasColumnName("elo_bracket");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalMinute")
                        .HasColumnType("integer");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TeamPosition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("TotalCsDiff")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDamageDiff")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalGoldDiff")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalKillsDiff")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalLevelDiff")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalXpDiff")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId", "TeamPosition", "Patch", "IntervalMinute", "EloBracket")
                        .IsUnique();

                    b.ToTable("champion_timeline_lead_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.DiscoveryCursor", b =>
                {
                    b.Property<string>("PlatformId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlatformId");

                    b.ToTable("discovery_cursors", (string)null);
                });

            modelBuilder.Entity("Data.Entities.JungleFirstClear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("FullClearTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<List<JungleClearStep>>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("jungle_first_clears", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MainCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<long>("ChampionPoints")
                        .HasColumnType("bigint");

                    b.Property<int>("ChampionRankInMasteryTop")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastPlayTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ObservedGames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ObservedWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ScoredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("PlatformId", "Puuid", "ChampionId")
                        .IsUnique();

                    b.HasIndex("PlatformId", "Status", "Score");

                    b.ToTable("main_candidates", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MainChampionStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionMatches")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExtendedSample")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOtp")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<double>("PlayRate")
                        .HasColumnType("double precision");

                    b.Property<List<PositionStat>>("PositionBreakdown")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId")
                        .HasDatabaseName("IX_main_champion_stats_is_main_champion")
                        .HasFilter("\"IsMain\"");

                    b.HasIndex("PlatformId", "IsMain");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("PlatformId", "IsMain"), new[] { "Puuid" });

                    b.HasIndex("PlatformId", "Puuid");

                    b.HasIndex("PlatformId", "Puuid", "ChampionId")
                        .IsUnique();

                    b.ToTable("main_champion_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GameDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("GameStartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("PowerspikeAggregated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<bool>("TimelineIngested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("QueueId")
                        .HasDatabaseName("IX_matches_powerspike_pending")
                        .HasFilter("\"PowerspikeAggregated\" = false");

                    b.HasIndex("TimelineIngested")
                        .HasDatabaseName("IX_matches_timeline_ingested");

                    b.HasIndex("PlatformId", "QueueId", "GameStartTimeUtc")
                        .HasDatabaseName("IX_matches_platform_queue_game_start");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<string>("EloBracket")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("")
                        .HasColumnName("elo_bracket");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<string>("IndividualPosition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Item0")
                        .HasColumnType("integer");

                    b.Property<int>("Item1")
                        .HasColumnType("integer");

                    b.Property<int>("Item2")
                        .HasColumnType("integer");

                    b.Property<int>("Item3")
                        .HasColumnType("integer");

                    b.Property<int>("Item4")
                        .HasColumnType("integer");

                    b.Property<int>("Item5")
                        .HasColumnType("integer");

                    b.Property<int>("Item6")
                        .HasColumnType("integer");

                    b.Property<List<ItemEvent>>("ItemEvents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("NeutralMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PerksDefense")
                        .HasColumnType("integer");

                    b.Property<int>("PerksFlex")
                        .HasColumnType("integer");

                    b.Property<int>("PerksOffense")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryStyleId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("RiotAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<List<SkillEvent>>("SkillEvents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SubStyleId")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner2Id")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SummonerName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamPosition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalDamageDealtToChampions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("TrinketItemId")
                        .HasColumnType("integer");

                    b.Property<int>("VisionScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RiotAccountId");

                    b.HasIndex("MatchId", "ParticipantId")
                        .IsUnique();

                    b.HasIndex("Puuid", "MatchId")
                        .HasDatabaseName("IX_match_participants_puuid_match");

                    b.HasIndex(new[] { "ChampionId", "TeamPosition", "EloBracket" }, "IX_match_participants_champion_position_full");

                    b.HasIndex(new[] { "ChampionId", "TeamPosition", "EloBracket" }, "IX_match_participants_champion_position_tracked")
                        .HasFilter("\"RiotAccountId\" IS NOT NULL");

                    b.ToTable("match_participants", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MatchParticipantKillPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("TimestampMs")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "ParticipantId");

                    b.ToTable("match_participant_kill_positions", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MatchParticipantTimelineSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DamageToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalMinute")
                        .HasColumnType("integer");

                    b.Property<int>("JungleMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("MinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("TimestampMs")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGold")
                        .HasColumnType("integer");

                    b.Property<int>("WardsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("WardsPlaced")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "ParticipantId", "IntervalMinute")
                        .IsUnique();

                    b.ToTable("match_participant_timeline_snapshots", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ParticipantPerkSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PerkSelectionCatalogId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerkSelectionCatalogId");

                    b.HasIndex("MatchId", "ParticipantId", "PerkSelectionCatalogId")
                        .IsUnique();

                    b.ToTable("participant_perk_selections", (string)null);
                });

            modelBuilder.Entity("Data.Entities.PerkSelectionCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PerkId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("StyleDescription")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StyleId", "SelectionIndex", "PerkId", "StyleDescription")
                        .IsUnique();

                    b.ToTable("perk_selection_catalog", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("Data.Entities.PowerspikeSigmaStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AggregatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalMinute")
                        .HasColumnType("integer");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<long>("SampleCount")
                        .HasColumnType("bigint");

                    b.Property<double>("SumDamageDiff")
                        .HasColumnType("double precision");

                    b.Property<double>("SumDamageDiffSq")
                        .HasColumnType("double precision");

                    b.Property<double>("SumGoldDiff")
                        .HasColumnType("double precision");

                    b.Property<double>("SumGoldDiffSq")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("QueueId", "IntervalMinute")
                        .IsUnique();

                    b.ToTable("powerspike_sigma_stats", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ProcessRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("IterationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Summary")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IterationId", "StartedAtUtc")
                        .HasFilter("\"IterationId\" IS NOT NULL");

                    b.HasIndex("ProcessName", "StartedAtUtc");

                    b.ToTable("process_runs", (string)null);
                });

            modelBuilder.Entity("Data.Entities.RankSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int?>("Losses")
                        .HasColumnType("integer");

                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RiotAccountId", "CapturedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_rank_snapshots_account_captured");

                    b.ToTable("rank_snapshots", (string)null);
                });

            modelBuilder.Entity("Data.Entities.RiotAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastMainCalcAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMatchIngestAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastProfileSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRankSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MatchIngestClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchIngestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("SummonerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SummonerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("TagLine")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.HasIndex("Score")
                        .HasDatabaseName("IX_riot_accounts_score");

                    b.HasIndex("GameName", "TagLine", "PlatformId")
                        .IsUnique();

                    b.HasIndex("MatchIngestStatus", "MatchIngestClaimedAtUtc", "LastMatchIngestAtUtc")
                        .HasDatabaseName("IX_riot_accounts_ingest_claim_lease")
                        .HasFilter("\"MatchIngestStatus\" <> 0");

                    b.ToTable("riot_accounts", (string)null);
                });

            modelBuilder.Entity("Data.Entities.SeedRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedPuuid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ResolvedRiotAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TagLine")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("seed_requests", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ChampionAggregatePattern", b =>
                {
                    b.HasOne("Data.Entities.ChampionDimBuild", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.ChampionDimRunePage", "RunePage")
                        .WithMany()
                        .HasForeignKey("RunePageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.ChampionAggregateScope", "Scope")
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.ChampionDimSkillOrder", "SkillOrder")
                        .WithMany()
                        .HasForeignKey("SkillOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.ChampionDimSpellPair", "SpellPair")
                        .WithMany()
                        .HasForeignKey("SpellPairId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.ChampionDimStarterItems", "StarterItems")
                        .WithMany()
                        .HasForeignKey("StarterItemsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("RunePage");

                    b.Navigation("Scope");

                    b.Navigation("SkillOrder");

                    b.Navigation("SpellPair");

                    b.Navigation("StarterItems");
                });

            modelBuilder.Entity("Data.Entities.ChampionAggregateScope", b =>
                {
                    b.HasOne("Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Data.Entities.JungleFirstClear", b =>
                {
                    b.HasOne("Data.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.MatchParticipant", b =>
                {
                    b.HasOne("Data.Entities.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId");

                    b.Navigation("Match");

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Data.Entities.MatchParticipantKillPosition", b =>
                {
                    b.HasOne("Data.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.MatchParticipantTimelineSnapshot", b =>
                {
                    b.HasOne("Data.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.ParticipantPerkSelection", b =>
                {
                    b.HasOne("Data.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.PerkSelectionCatalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("PerkSelectionCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Data.Entities.RankSnapshot", b =>
                {
                    b.HasOne("Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Data.Entities.RiotAccount", b =>
                {
                    b.HasOne("Data.Entities.Persona", "Persona")
                        .WithMany("RiotAccounts")
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Data.Entities.Match", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Data.Entities.Persona", b =>
                {
                    b.Navigation("RiotAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
