using System.Globalization;
using Data;
using Data.DataQuality;
using Microsoft.EntityFrameworkCore;
using TrueMain.Options;
using TrueMain.ReadModels.Ops;

namespace TrueMain.Services.Ops.DataQuality;

/// <summary>
/// The duplicate-dimension-rows detector: groups each audited <c>champion_dim_*</c> table on
/// the canonical key its UNIQUE index and CHECK are built from (#1418), plus the
/// non-canonical-order leading indicator.
/// </summary>
internal sealed class DuplicateDimensionsDetector(TrueMainDbContext db)
{
    public async Task<DataQualityDetectorReadModel> BuildAsync(
        DataQualityDetectorOptions settings,
        CancellationToken ct)
    {
        var rows = new List<DataQualityDetectorRowReadModel>();
        long duplicateGroups = 0;
        long nonCanonicalRows = 0;

        foreach (var audit in ChampionDimensionCanonicalKeys.AuditedTables)
        {
            var duplicates = await CountDuplicateGroupsAsync(audit, ct);
            var nonCanonical = audit.NonCanonicalPredicate is null
                ? (long?)null
                : await CountNonCanonicalAsync(audit, ct);

            duplicateGroups += duplicates;
            nonCanonicalRows += nonCanonical ?? 0;

            var duplicateStatus = DataQualityDetectorEvaluator.Classify(
                duplicates,
                settings.DuplicateDimensionGroupsAmber,
                settings.DuplicateDimensionGroupsRed);

            // The leading indicator only votes when it exists. Unknown means "the answer
            // could not be measured", and the answer here is the duplicate count — which
            // was measured. A signal that is *permanently* inapplicable by design (a
            // starter basket's key is generated by Postgres, so no stored order carries
            // identity) would otherwise pin that row to unknown for ever, which teaches
            // the operator to ignore the colour.
            var statuses = nonCanonical is null
                ? new[] { duplicateStatus }
                :
                [
                    duplicateStatus,
                    DataQualityDetectorEvaluator.Classify(
                        nonCanonical,
                        settings.NonCanonicalDimensionRowsAmber,
                        settings.NonCanonicalDimensionRowsRed)
                ];

            var note = nonCanonical is null
                // Inapplicable, not unchecked: the row has no stored order to be out of.
                ? audit.Rationale
                : string.Create(
                    CultureInfo.InvariantCulture,
                    $"{audit.Rationale} {nonCanonical} row(s) stored outside canonical order.");

            rows.Add(new DataQualityDetectorRowReadModel
            {
                Label = audit.TableName,
                Status = DataQualityDetectorEvaluator.Worst(statuses).ToWireName(),
                Value = duplicates,
                ValueLabel = string.Create(CultureInfo.InvariantCulture, $"{duplicates} duplicate group(s)"),
                Note = note
            });
        }

        var exempt = string.Join(
            " ",
            ChampionDimensionCanonicalKeys.ExemptTables.Select(table => $"{table.TableName}: {table.Reason}"));

        var duplicateCardStatus = DataQualityDetectorEvaluator.Worst(rows.Select(DetectorCards.ParseStatus));

        return new DataQualityDetectorReadModel
        {
            Key = "duplicateDimensionRows",
            Title = "Duplicate dimension rows",
            Status = duplicateCardStatus.ToWireName(),
            Count = duplicateGroups,
            CountLabel = "canonical-key groups holding more than one row",
            // Worded from the verdict. A table holding rows outside canonical order but
            // no duplicate yet turns this card amber, and a headline computed from the
            // duplicate count alone would pair that badge with "every row is unique".
            Headline = duplicateCardStatus switch
            {
                DetectorStatus.Green => "Every audited dimension row is unique under its canonical key.",
                DetectorStatus.Unknown => "Part of the dimension audit could not be measured.",
                _ when duplicateGroups > 0 => string.Create(
                    CultureInfo.InvariantCulture,
                    $"{duplicateGroups} canonical-key group(s) hold more than one row — those games are split across rows, the #911 failure. The schema forbids this, so a constraint is missing."),
                _ => string.Create(
                    CultureInfo.InvariantCulture,
                    $"{nonCanonicalRows} row(s) are stored outside canonical order — nothing is split yet, but the reader's canonical lookup will miss them and mint a second row (#911). The schema forbids this, so a constraint is missing."),
            },
            SourceNote = "Groups each champion_dim_* table on the same canonical key its UNIQUE index and "
                + "CHECK are built from (#1418), so a count above zero means a constraint went missing "
                + "rather than a repair being owed. Not audited — " + exempt,
            Rows = rows,
            Thresholds =
            [
                DetectorCards.Threshold("duplicate groups", settings.DuplicateDimensionGroupsAmber, settings.DuplicateDimensionGroupsRed, "count"),
                DetectorCards.Threshold("non-canonical rows", settings.NonCanonicalDimensionRowsAmber, settings.NonCanonicalDimensionRowsRed, "count")
            ]
        };
    }

    private async Task<long> CountDuplicateGroupsAsync(ChampionDimensionAudit audit, CancellationToken ct)
    {
        // The SQL fragments are compile-time constants owned by ChampionDimensionCanonicalKeys,
        // never user input, so raw interpolation is safe here — and necessary, since a
        // GROUP BY expression list cannot be a parameter.
        var sql = $"""
            SELECT count(*)::bigint AS "Value"
            FROM (
                SELECT 1
                FROM {audit.FromSql}
                GROUP BY {audit.CanonicalKeyExpression}
                HAVING count(*) > 1
            ) duplicate_groups
            """;

        return await db.Database.SqlQueryRaw<long>(sql).SingleAsync(ct);
    }

    private async Task<long> CountNonCanonicalAsync(ChampionDimensionAudit audit, CancellationToken ct)
    {
        var sql = $"""
            SELECT count(*)::bigint AS "Value"
            FROM {audit.TableName}
            WHERE {audit.NonCanonicalPredicate}
            """;

        return await db.Database.SqlQueryRaw<long>(sql).SingleAsync(ct);
    }
}
