// <auto-generated />
using System;
using System.Reflection;
using Data.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ChampionProfileStatEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Data.Entities.ChampionProfileStat",
                typeof(ChampionProfileStat),
                baseEntityType,
                propertyCount: 34,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var abilityPowerGames = runtimeEntityType.AddProperty(
                "AbilityPowerGames",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("AbilityPowerGames", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<AbilityPowerGames>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            abilityPowerGames.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var aggregatedAtUtc = runtimeEntityType.AddProperty(
                "AggregatedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("AggregatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<AggregatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            aggregatedAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var armorPenetrationGames = runtimeEntityType.AddProperty(
                "ArmorPenetrationGames",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("ArmorPenetrationGames", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<ArmorPenetrationGames>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            armorPenetrationGames.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var championId = runtimeEntityType.AddProperty(
                "ChampionId",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("ChampionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<ChampionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            championId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var critGames = runtimeEntityType.AddProperty(
                "CritGames",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("CritGames", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<CritGames>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            critGames.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var damageSelfMitigatedSum = runtimeEntityType.AddProperty(
                "DamageSelfMitigatedSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("DamageSelfMitigatedSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<DamageSelfMitigatedSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            damageSelfMitigatedSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var damageShieldedOnTeammatesSum = runtimeEntityType.AddProperty(
                "DamageShieldedOnTeammatesSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("DamageShieldedOnTeammatesSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<DamageShieldedOnTeammatesSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            damageShieldedOnTeammatesSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var damageTakenSum = runtimeEntityType.AddProperty(
                "DamageTakenSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("DamageTakenSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<DamageTakenSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            damageTakenSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var gameDurationSecondsSum = runtimeEntityType.AddProperty(
                "GameDurationSecondsSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("GameDurationSecondsSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<GameDurationSecondsSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            gameDurationSecondsSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var games = runtimeEntityType.AddProperty(
                "Games",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("Games", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<Games>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            games.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var goldLeadAt10Sum = runtimeEntityType.AddProperty(
                "GoldLeadAt10Sum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("GoldLeadAt10Sum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<GoldLeadAt10Sum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            goldLeadAt10Sum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var goldLeadAt15Sum = runtimeEntityType.AddProperty(
                "GoldLeadAt15Sum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("GoldLeadAt15Sum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<GoldLeadAt15Sum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            goldLeadAt15Sum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var healsOnTeammatesSum = runtimeEntityType.AddProperty(
                "HealsOnTeammatesSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("HealsOnTeammatesSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<HealsOnTeammatesSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            healsOnTeammatesSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var isRanged = runtimeEntityType.AddProperty(
                "IsRanged",
                typeof(bool?),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("IsRanged", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<IsRanged>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            isRanged.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var itemGames = runtimeEntityType.AddProperty(
                "ItemGames",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("ItemGames", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<ItemGames>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            itemGames.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var killsBy10Sum = runtimeEntityType.AddProperty(
                "KillsBy10Sum",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("KillsBy10Sum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<KillsBy10Sum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            killsBy10Sum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var laneGamesAt10 = runtimeEntityType.AddProperty(
                "LaneGamesAt10",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("LaneGamesAt10", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<LaneGamesAt10>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            laneGamesAt10.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var laneGamesAt15 = runtimeEntityType.AddProperty(
                "LaneGamesAt15",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("LaneGamesAt15", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<LaneGamesAt15>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            laneGamesAt15.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var magicDamageToChampionsSum = runtimeEntityType.AddProperty(
                "MagicDamageToChampionsSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("MagicDamageToChampionsSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<MagicDamageToChampionsSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            magicDamageToChampionsSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var onHitGames = runtimeEntityType.AddProperty(
                "OnHitGames",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("OnHitGames", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<OnHitGames>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            onHitGames.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var patch = runtimeEntityType.AddProperty(
                "Patch",
                typeof(string),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("Patch", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<Patch>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 16);
            patch.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var physicalDamageToChampionsSum = runtimeEntityType.AddProperty(
                "PhysicalDamageToChampionsSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("PhysicalDamageToChampionsSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<PhysicalDamageToChampionsSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            physicalDamageToChampionsSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var position = runtimeEntityType.AddProperty(
                "Position",
                typeof(string),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("Position", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<Position>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 16);
            position.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var tankGames = runtimeEntityType.AddProperty(
                "TankGames",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("TankGames", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<TankGames>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            tankGames.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var teamDamageTakenGames = runtimeEntityType.AddProperty(
                "TeamDamageTakenGames",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("TeamDamageTakenGames", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<TeamDamageTakenGames>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            teamDamageTakenGames.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var teamDamageTakenSum = runtimeEntityType.AddProperty(
                "TeamDamageTakenSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("TeamDamageTakenSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<TeamDamageTakenSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            teamDamageTakenSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var timeCCingOthersSum = runtimeEntityType.AddProperty(
                "TimeCCingOthersSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("TimeCCingOthersSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<TimeCCingOthersSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            timeCCingOthersSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var totalHealSum = runtimeEntityType.AddProperty(
                "TotalHealSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("TotalHealSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<TotalHealSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            totalHealSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var totalTimeCCDealtSum = runtimeEntityType.AddProperty(
                "TotalTimeCCDealtSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("TotalTimeCCDealtSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<TotalTimeCCDealtSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            totalTimeCCDealtSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var trueDamageToChampionsSum = runtimeEntityType.AddProperty(
                "TrueDamageToChampionsSum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("TrueDamageToChampionsSum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<TrueDamageToChampionsSum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            trueDamageToChampionsSum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var wins = runtimeEntityType.AddProperty(
                "Wins",
                typeof(int),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("Wins", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<Wins>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            wins.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var xpLeadAt10Sum = runtimeEntityType.AddProperty(
                "XpLeadAt10Sum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("XpLeadAt10Sum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<XpLeadAt10Sum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            xpLeadAt10Sum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var xpLeadAt15Sum = runtimeEntityType.AddProperty(
                "XpLeadAt15Sum",
                typeof(long),
                propertyInfo: typeof(ChampionProfileStat).GetProperty("XpLeadAt15Sum", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionProfileStat).GetField("<XpLeadAt15Sum>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            xpLeadAt15Sum.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { patch, championId, position },
                unique: true);
            index.AddAnnotation("Relational:Name", "IX_champion_profile_stats_grain");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "champion_profile_stats");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
