// <auto-generated />
using System;
using System.Reflection;
using Data.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ChampionDimRunePageEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Data.Entities.ChampionDimRunePage",
                typeof(ChampionDimRunePage),
                baseEntityType,
                propertyCount: 12,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var primaryKeystoneId = runtimeEntityType.AddProperty(
                "PrimaryKeystoneId",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("PrimaryKeystoneId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<PrimaryKeystoneId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            primaryKeystoneId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var primaryPerk1Id = runtimeEntityType.AddProperty(
                "PrimaryPerk1Id",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("PrimaryPerk1Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<PrimaryPerk1Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            primaryPerk1Id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var primaryPerk2Id = runtimeEntityType.AddProperty(
                "PrimaryPerk2Id",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("PrimaryPerk2Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<PrimaryPerk2Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            primaryPerk2Id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var primaryPerk3Id = runtimeEntityType.AddProperty(
                "PrimaryPerk3Id",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("PrimaryPerk3Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<PrimaryPerk3Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            primaryPerk3Id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var primaryStyleId = runtimeEntityType.AddProperty(
                "PrimaryStyleId",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("PrimaryStyleId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<PrimaryStyleId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            primaryStyleId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var secondaryPerk1Id = runtimeEntityType.AddProperty(
                "SecondaryPerk1Id",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("SecondaryPerk1Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<SecondaryPerk1Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            secondaryPerk1Id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var secondaryPerk2Id = runtimeEntityType.AddProperty(
                "SecondaryPerk2Id",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("SecondaryPerk2Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<SecondaryPerk2Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            secondaryPerk2Id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var secondaryStyleId = runtimeEntityType.AddProperty(
                "SecondaryStyleId",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("SecondaryStyleId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<SecondaryStyleId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            secondaryStyleId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var statDefense = runtimeEntityType.AddProperty(
                "StatDefense",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("StatDefense", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<StatDefense>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            statDefense.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var statFlex = runtimeEntityType.AddProperty(
                "StatFlex",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("StatFlex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<StatFlex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            statFlex.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var statOffense = runtimeEntityType.AddProperty(
                "StatOffense",
                typeof(int),
                propertyInfo: typeof(ChampionDimRunePage).GetProperty("StatOffense", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionDimRunePage).GetField("<StatOffense>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            statOffense.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { primaryStyleId, primaryKeystoneId, primaryPerk1Id, primaryPerk2Id, primaryPerk3Id, secondaryStyleId, secondaryPerk1Id, secondaryPerk2Id, statOffense, statFlex, statDefense },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "champion_dim_rune_pages");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
