// <auto-generated />
using System;
using System.Reflection;
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ChampionAggregatePatternEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Data.Entities.ChampionAggregatePattern",
                typeof(ChampionAggregatePattern),
                baseEntityType,
                propertyCount: 9,
                navigationCount: 6,
                foreignKeyCount: 6,
                unnamedIndexCount: 11,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var buildId = runtimeEntityType.AddProperty(
                "BuildId",
                typeof(Guid),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("BuildId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<BuildId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            buildId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var games = runtimeEntityType.AddProperty(
                "Games",
                typeof(int),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("Games", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<Games>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            games.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var runePageId = runtimeEntityType.AddProperty(
                "RunePageId",
                typeof(Guid),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("RunePageId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<RunePageId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            runePageId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var scopeId = runtimeEntityType.AddProperty(
                "ScopeId",
                typeof(Guid),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("ScopeId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<ScopeId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            scopeId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var skillOrderId = runtimeEntityType.AddProperty(
                "SkillOrderId",
                typeof(Guid),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("SkillOrderId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<SkillOrderId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            skillOrderId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var spellPairId = runtimeEntityType.AddProperty(
                "SpellPairId",
                typeof(Guid),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("SpellPairId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<SpellPairId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            spellPairId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var starterItemsId = runtimeEntityType.AddProperty(
                "StarterItemsId",
                typeof(Guid),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("StarterItemsId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<StarterItemsId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            starterItemsId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var wins = runtimeEntityType.AddProperty(
                "Wins",
                typeof(int),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("Wins", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<Wins>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            wins.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { buildId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { runePageId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { skillOrderId });

            var index2 = runtimeEntityType.AddIndex(
                new[] { spellPairId });

            var index3 = runtimeEntityType.AddIndex(
                new[] { starterItemsId });

            var index4 = runtimeEntityType.AddIndex(
                new[] { scopeId, buildId });

            var index5 = runtimeEntityType.AddIndex(
                new[] { scopeId, runePageId });

            var index6 = runtimeEntityType.AddIndex(
                new[] { scopeId, skillOrderId });

            var index7 = runtimeEntityType.AddIndex(
                new[] { scopeId, spellPairId });

            var index8 = runtimeEntityType.AddIndex(
                new[] { scopeId, starterItemsId });

            var index9 = runtimeEntityType.AddIndex(
                new[] { scopeId, buildId, runePageId, skillOrderId, spellPairId, starterItemsId },
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("BuildId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var build = declaringEntityType.AddNavigation("Build",
                runtimeForeignKey,
                onDependent: true,
                typeof(ChampionDimBuild),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("Build", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<Build>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("RunePageId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var runePage = declaringEntityType.AddNavigation("RunePage",
                runtimeForeignKey,
                onDependent: true,
                typeof(ChampionDimRunePage),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("RunePage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<RunePage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ScopeId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var scope = declaringEntityType.AddNavigation("Scope",
                runtimeForeignKey,
                onDependent: true,
                typeof(ChampionAggregateScope),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("Scope", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<Scope>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SkillOrderId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var skillOrder = declaringEntityType.AddNavigation("SkillOrder",
                runtimeForeignKey,
                onDependent: true,
                typeof(ChampionDimSkillOrder),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("SkillOrder", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<SkillOrder>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey5(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SpellPairId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var spellPair = declaringEntityType.AddNavigation("SpellPair",
                runtimeForeignKey,
                onDependent: true,
                typeof(ChampionDimSpellPair),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("SpellPair", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<SpellPair>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey6(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("StarterItemsId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var starterItems = declaringEntityType.AddNavigation("StarterItems",
                runtimeForeignKey,
                onDependent: true,
                typeof(ChampionDimStarterItems),
                propertyInfo: typeof(ChampionAggregatePattern).GetProperty("StarterItems", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ChampionAggregatePattern).GetField("<StarterItems>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "champion_aggregate_patterns");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
