// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Data.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MainChampionStatEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Data.Entities.MainChampionStat",
                typeof(MainChampionStat),
                baseEntityType,
                propertyCount: 13,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(MainChampionStat).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var calculatedAtUtc = runtimeEntityType.AddProperty(
                "CalculatedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(MainChampionStat).GetProperty("CalculatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<CalculatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            calculatedAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var championId = runtimeEntityType.AddProperty(
                "ChampionId",
                typeof(int),
                propertyInfo: typeof(MainChampionStat).GetProperty("ChampionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<ChampionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            championId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var championMatches = runtimeEntityType.AddProperty(
                "ChampionMatches",
                typeof(int),
                propertyInfo: typeof(MainChampionStat).GetProperty("ChampionMatches", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<ChampionMatches>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            championMatches.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var isExtendedSample = runtimeEntityType.AddProperty(
                "IsExtendedSample",
                typeof(bool),
                propertyInfo: typeof(MainChampionStat).GetProperty("IsExtendedSample", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<IsExtendedSample>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            isExtendedSample.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            isExtendedSample.AddAnnotation("Relational:DefaultValue", false);

            var isMain = runtimeEntityType.AddProperty(
                "IsMain",
                typeof(bool),
                propertyInfo: typeof(MainChampionStat).GetProperty("IsMain", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<IsMain>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isMain.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var isOtp = runtimeEntityType.AddProperty(
                "IsOtp",
                typeof(bool),
                propertyInfo: typeof(MainChampionStat).GetProperty("IsOtp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<IsOtp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isOtp.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var platformId = runtimeEntityType.AddProperty(
                "PlatformId",
                typeof(string),
                propertyInfo: typeof(MainChampionStat).GetProperty("PlatformId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<PlatformId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 8);
            platformId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var playRate = runtimeEntityType.AddProperty(
                "PlayRate",
                typeof(double),
                propertyInfo: typeof(MainChampionStat).GetProperty("PlayRate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<PlayRate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                precision: 18,
                scale: 6,
                sentinel: 0.0);
            playRate.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var positionBreakdown = runtimeEntityType.AddProperty(
                "PositionBreakdown",
                typeof(List<PositionStat>),
                propertyInfo: typeof(MainChampionStat).GetProperty("PositionBreakdown", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<PositionBreakdown>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            positionBreakdown.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            positionBreakdown.AddAnnotation("Relational:ColumnType", "jsonb");

            var primaryPosition = runtimeEntityType.AddProperty(
                "PrimaryPosition",
                typeof(string),
                propertyInfo: typeof(MainChampionStat).GetProperty("PrimaryPosition", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<PrimaryPosition>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            primaryPosition.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var puuid = runtimeEntityType.AddProperty(
                "Puuid",
                typeof(string),
                propertyInfo: typeof(MainChampionStat).GetProperty("Puuid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<Puuid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 128);
            puuid.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var totalMatches = runtimeEntityType.AddProperty(
                "TotalMatches",
                typeof(int),
                propertyInfo: typeof(MainChampionStat).GetProperty("TotalMatches", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MainChampionStat).GetField("<TotalMatches>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            totalMatches.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { championId });
            index.AddAnnotation("Relational:Filter", "\"IsMain\"");
            index.AddAnnotation("Relational:Name", "IX_main_champion_stats_is_main_champion");

            var index0 = runtimeEntityType.AddIndex(
                new[] { platformId, isMain });

            var index1 = runtimeEntityType.AddIndex(
                new[] { platformId, puuid, championId },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "main_champion_stats");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
