// <auto-generated />
using System;
using System.Reflection;
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MatchParticipantTimelineSnapshotEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Data.Entities.MatchParticipantTimelineSnapshot",
                typeof(MatchParticipantTimelineSnapshot),
                baseEntityType,
                propertyCount: 14,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var damageToChampions = runtimeEntityType.AddProperty(
                "DamageToChampions",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("DamageToChampions", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<DamageToChampions>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            damageToChampions.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var intervalMinute = runtimeEntityType.AddProperty(
                "IntervalMinute",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("IntervalMinute", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<IntervalMinute>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            intervalMinute.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var jungleMinionsKilled = runtimeEntityType.AddProperty(
                "JungleMinionsKilled",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("JungleMinionsKilled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<JungleMinionsKilled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            jungleMinionsKilled.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var kills = runtimeEntityType.AddProperty(
                "Kills",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("Kills", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<Kills>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            kills.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var level = runtimeEntityType.AddProperty(
                "Level",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("Level", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<Level>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            level.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var matchId = runtimeEntityType.AddProperty(
                "MatchId",
                typeof(string),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("MatchId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<MatchId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            matchId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var minionsKilled = runtimeEntityType.AddProperty(
                "MinionsKilled",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("MinionsKilled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<MinionsKilled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            minionsKilled.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var participantId = runtimeEntityType.AddProperty(
                "ParticipantId",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("ParticipantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<ParticipantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            participantId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var timestampMs = runtimeEntityType.AddProperty(
                "TimestampMs",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("TimestampMs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<TimestampMs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            timestampMs.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var totalGold = runtimeEntityType.AddProperty(
                "TotalGold",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("TotalGold", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<TotalGold>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            totalGold.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var wardsKilled = runtimeEntityType.AddProperty(
                "WardsKilled",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("WardsKilled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<WardsKilled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            wardsKilled.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var wardsPlaced = runtimeEntityType.AddProperty(
                "WardsPlaced",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("WardsPlaced", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<WardsPlaced>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            wardsPlaced.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var xp = runtimeEntityType.AddProperty(
                "Xp",
                typeof(int),
                propertyInfo: typeof(MatchParticipantTimelineSnapshot).GetProperty("Xp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MatchParticipantTimelineSnapshot).GetField("<Xp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            xp.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { matchId, participantId, intervalMinute },
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MatchId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "match_participant_timeline_snapshots");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
