// <auto-generated />
using System;
using System.Reflection;
using Data.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MatchEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Data.Entities.Match",
                typeof(Match),
                baseEntityType,
                propertyCount: 19,
                navigationCount: 1,
                unnamedIndexCount: 6,
                namedIndexCount: 6,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(string),
                propertyInfo: typeof(Match).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 32);
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var bansAggregated = runtimeEntityType.AddProperty(
                "BansAggregated",
                typeof(bool),
                propertyInfo: typeof(Match).GetProperty("BansAggregated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<BansAggregated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            bansAggregated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            bansAggregated.AddAnnotation("Relational:DefaultValue", false);

            var createdAtUtc = runtimeEntityType.AddProperty(
                "CreatedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(Match).GetProperty("CreatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<CreatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAtUtc.AddAnnotation("Relational:DefaultValueSql", "now()");

            var gameDurationSeconds = runtimeEntityType.AddProperty(
                "GameDurationSeconds",
                typeof(int),
                propertyInfo: typeof(Match).GetProperty("GameDurationSeconds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<GameDurationSeconds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            gameDurationSeconds.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var gameMode = runtimeEntityType.AddProperty(
                "GameMode",
                typeof(string),
                propertyInfo: typeof(Match).GetProperty("GameMode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<GameMode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            gameMode.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var gameStartTimeUtc = runtimeEntityType.AddProperty(
                "GameStartTimeUtc",
                typeof(DateTime),
                propertyInfo: typeof(Match).GetProperty("GameStartTimeUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<GameStartTimeUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            gameStartTimeUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var gameType = runtimeEntityType.AddProperty(
                "GameType",
                typeof(string),
                propertyInfo: typeof(Match).GetProperty("GameType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<GameType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            gameType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var gameVersion = runtimeEntityType.AddProperty(
                "GameVersion",
                typeof(string),
                propertyInfo: typeof(Match).GetProperty("GameVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<GameVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            gameVersion.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var itemContextAggregated = runtimeEntityType.AddProperty(
                "ItemContextAggregated",
                typeof(bool),
                propertyInfo: typeof(Match).GetProperty("ItemContextAggregated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<ItemContextAggregated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            itemContextAggregated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            itemContextAggregated.AddAnnotation("Relational:DefaultValue", false);

            var mapId = runtimeEntityType.AddProperty(
                "MapId",
                typeof(int),
                propertyInfo: typeof(Match).GetProperty("MapId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<MapId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            mapId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var matchupLeadAggregated = runtimeEntityType.AddProperty(
                "MatchupLeadAggregated",
                typeof(bool),
                propertyInfo: typeof(Match).GetProperty("MatchupLeadAggregated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<MatchupLeadAggregated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            matchupLeadAggregated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            matchupLeadAggregated.AddAnnotation("Relational:DefaultValue", false);

            var patch = runtimeEntityType.AddProperty(
                "Patch",
                typeof(string),
                propertyInfo: typeof(Match).GetProperty("Patch", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<Patch>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                maxLength: 32);
            patch.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            patch.AddAnnotation("Relational:ComputedColumnSql", "((regexp_match(\"GameVersion\", '^[\\s.]*([+-]?[0-9]{1,9})[\\s]*\\.[\\s.]*([+-]?[0-9]{1,9})[\\s]*(\\.|$)'))[1])::int::text || '.' || ((regexp_match(\"GameVersion\", '^[\\s.]*([+-]?[0-9]{1,9})[\\s]*\\.[\\s.]*([+-]?[0-9]{1,9})[\\s]*(\\.|$)'))[2])::int::text");
            patch.AddAnnotation("Relational:IsStored", true);

            var platformId = runtimeEntityType.AddProperty(
                "PlatformId",
                typeof(string),
                propertyInfo: typeof(Match).GetProperty("PlatformId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<PlatformId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 8);
            platformId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var powerspikeAggregated = runtimeEntityType.AddProperty(
                "PowerspikeAggregated",
                typeof(bool),
                propertyInfo: typeof(Match).GetProperty("PowerspikeAggregated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<PowerspikeAggregated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            powerspikeAggregated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            powerspikeAggregated.AddAnnotation("Relational:DefaultValue", false);

            var profileAggregated = runtimeEntityType.AddProperty(
                "ProfileAggregated",
                typeof(bool),
                propertyInfo: typeof(Match).GetProperty("ProfileAggregated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<ProfileAggregated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            profileAggregated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            profileAggregated.AddAnnotation("Relational:DefaultValue", false);

            var queueId = runtimeEntityType.AddProperty(
                "QueueId",
                typeof(int),
                propertyInfo: typeof(Match).GetProperty("QueueId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<QueueId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            queueId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var synergyAggregated = runtimeEntityType.AddProperty(
                "SynergyAggregated",
                typeof(bool),
                propertyInfo: typeof(Match).GetProperty("SynergyAggregated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<SynergyAggregated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            synergyAggregated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            synergyAggregated.AddAnnotation("Relational:DefaultValue", false);

            var timelineIngested = runtimeEntityType.AddProperty(
                "TimelineIngested",
                typeof(bool),
                propertyInfo: typeof(Match).GetProperty("TimelineIngested", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<TimelineIngested>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            timelineIngested.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            timelineIngested.AddAnnotation("Relational:DefaultValue", false);

            var timelineSnapshotsPruned = runtimeEntityType.AddProperty(
                "TimelineSnapshotsPruned",
                typeof(bool),
                propertyInfo: typeof(Match).GetProperty("TimelineSnapshotsPruned", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Match).GetField("<TimelineSnapshotsPruned>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            timelineSnapshotsPruned.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            timelineSnapshotsPruned.AddAnnotation("Relational:DefaultValue", false);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { platformId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { queueId });
            index0.AddAnnotation("Relational:Filter", "\"PowerspikeAggregated\" = false");
            index0.AddAnnotation("Relational:Name", "IX_matches_powerspike_pending");

            var index1 = runtimeEntityType.AddIndex(
                new[] { timelineIngested });
            index1.AddAnnotation("Relational:Name", "IX_matches_timeline_ingested");

            var index2 = runtimeEntityType.AddIndex(
                new[] { patch, queueId });
            index2.AddAnnotation("Relational:Name", "IX_matches_patch_queue");

            var index3 = runtimeEntityType.AddIndex(
                new[] { platformId, queueId, gameStartTimeUtc });
            index3.AddAnnotation("Relational:Name", "IX_matches_platform_queue_game_start");

            var index4 = runtimeEntityType.AddIndex(
                new[] { queueId, patch, platformId });
            index4.AddAnnotation("Relational:Name", "IX_matches_queue_patch_platform");

            var iX_matches_bans_pending = runtimeEntityType.AddIndex(
                new[] { queueId },
                name: "IX_matches_bans_pending");
            iX_matches_bans_pending.AddAnnotation("Relational:Filter", "\"BansAggregated\" = false");

            var iX_matches_item_context_pending = runtimeEntityType.AddIndex(
                new[] { queueId },
                name: "IX_matches_item_context_pending");
            iX_matches_item_context_pending.AddAnnotation("Relational:Filter", "\"ItemContextAggregated\" = false");

            var iX_matches_matchup_lead_pending = runtimeEntityType.AddIndex(
                new[] { queueId },
                name: "IX_matches_matchup_lead_pending");
            iX_matches_matchup_lead_pending.AddAnnotation("Relational:Filter", "\"MatchupLeadAggregated\" = false");

            var iX_matches_profile_pending = runtimeEntityType.AddIndex(
                new[] { queueId },
                name: "IX_matches_profile_pending");
            iX_matches_profile_pending.AddAnnotation("Relational:Filter", "\"ProfileAggregated\" = false");

            var iX_matches_snapshot_prune_pending = runtimeEntityType.AddIndex(
                new[] { queueId },
                name: "IX_matches_snapshot_prune_pending");
            iX_matches_snapshot_prune_pending.AddAnnotation("Relational:Filter", "\"PowerspikeAggregated\" = true AND \"TimelineSnapshotsPruned\" = false");

            var iX_matches_synergy_pending = runtimeEntityType.AddIndex(
                new[] { queueId },
                name: "IX_matches_synergy_pending");
            iX_matches_synergy_pending.AddAnnotation("Relational:Filter", "\"SynergyAggregated\" = false");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "matches");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
