// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Data.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RiotAccountEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Data.Entities.RiotAccount",
                typeof(RiotAccount),
                baseEntityType,
                propertyCount: 20,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(RiotAccount).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var createdAtUtc = runtimeEntityType.AddProperty(
                "CreatedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(RiotAccount).GetProperty("CreatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<CreatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            createdAtUtc.AddAnnotation("Relational:DefaultValueSql", "now()");

            var gameName = runtimeEntityType.AddProperty(
                "GameName",
                typeof(string),
                propertyInfo: typeof(RiotAccount).GetProperty("GameName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<GameName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            gameName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var lastMainCalcAtUtc = runtimeEntityType.AddProperty(
                "LastMainCalcAtUtc",
                typeof(DateTime?),
                propertyInfo: typeof(RiotAccount).GetProperty("LastMainCalcAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<LastMainCalcAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastMainCalcAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var lastMatchIngestAtUtc = runtimeEntityType.AddProperty(
                "LastMatchIngestAtUtc",
                typeof(DateTime?),
                propertyInfo: typeof(RiotAccount).GetProperty("LastMatchIngestAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<LastMatchIngestAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastMatchIngestAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var lastProfileSyncAtUtc = runtimeEntityType.AddProperty(
                "LastProfileSyncAtUtc",
                typeof(DateTime?),
                propertyInfo: typeof(RiotAccount).GetProperty("LastProfileSyncAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<LastProfileSyncAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastProfileSyncAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var lastRankSyncAtUtc = runtimeEntityType.AddProperty(
                "LastRankSyncAtUtc",
                typeof(DateTime?),
                propertyInfo: typeof(RiotAccount).GetProperty("LastRankSyncAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<LastRankSyncAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastRankSyncAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var matchIngestClaimedAtUtc = runtimeEntityType.AddProperty(
                "MatchIngestClaimedAtUtc",
                typeof(DateTime?),
                propertyInfo: typeof(RiotAccount).GetProperty("MatchIngestClaimedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<MatchIngestClaimedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            matchIngestClaimedAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var matchIngestStatus = runtimeEntityType.AddProperty(
                "MatchIngestStatus",
                typeof(MatchIngestStatus),
                propertyInfo: typeof(RiotAccount).GetProperty("MatchIngestStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<MatchIngestStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd);
            matchIngestStatus.SetSentinelFromProviderValue(0);
            matchIngestStatus.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            matchIngestStatus.AddAnnotation("Relational:DefaultValue", MatchIngestStatus.Idle);

            var personaId = runtimeEntityType.AddProperty(
                "PersonaId",
                typeof(Guid?),
                propertyInfo: typeof(RiotAccount).GetProperty("PersonaId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<PersonaId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            personaId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var platformId = runtimeEntityType.AddProperty(
                "PlatformId",
                typeof(string),
                propertyInfo: typeof(RiotAccount).GetProperty("PlatformId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<PlatformId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 8);
            platformId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var profileIconId = runtimeEntityType.AddProperty(
                "ProfileIconId",
                typeof(int),
                propertyInfo: typeof(RiotAccount).GetProperty("ProfileIconId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<ProfileIconId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            profileIconId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var puuid = runtimeEntityType.AddProperty(
                "Puuid",
                typeof(string),
                propertyInfo: typeof(RiotAccount).GetProperty("Puuid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<Puuid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 128);
            puuid.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var score = runtimeEntityType.AddProperty(
                "Score",
                typeof(int?),
                propertyInfo: typeof(RiotAccount).GetProperty("Score", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<Score>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            score.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(RiotAccountStatus),
                propertyInfo: typeof(RiotAccount).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd);
            status.SetSentinelFromProviderValue(0);
            status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            status.AddAnnotation("Relational:DefaultValue", RiotAccountStatus.Active);

            var summonerId = runtimeEntityType.AddProperty(
                "SummonerId",
                typeof(string),
                propertyInfo: typeof(RiotAccount).GetProperty("SummonerId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<SummonerId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 128);
            summonerId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var summonerLevel = runtimeEntityType.AddProperty(
                "SummonerLevel",
                typeof(int),
                propertyInfo: typeof(RiotAccount).GetProperty("SummonerLevel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<SummonerLevel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            summonerLevel.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var tagLine = runtimeEntityType.AddProperty(
                "TagLine",
                typeof(string),
                propertyInfo: typeof(RiotAccount).GetProperty("TagLine", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<TagLine>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 8);
            tagLine.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var updatedAtUtc = runtimeEntityType.AddProperty(
                "UpdatedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(RiotAccount).GetProperty("UpdatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<UpdatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            updatedAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            updatedAtUtc.AddAnnotation("Relational:DefaultValueSql", "now()");

            var xmin = runtimeEntityType.AddProperty(
                "xmin",
                typeof(uint),
                concurrencyToken: true,
                valueGenerated: ValueGenerated.OnAddOrUpdate,
                beforeSaveBehavior: PropertySaveBehavior.Ignore,
                afterSaveBehavior: PropertySaveBehavior.Ignore,
                sentinel: 0u);
            xmin.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            xmin.AddAnnotation("Relational:ColumnName", "xmin");
            xmin.AddAnnotation("Relational:ColumnType", "xid");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { personaId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { puuid },
                unique: true);

            var index1 = runtimeEntityType.AddIndex(
                new[] { score });
            index1.AddAnnotation("Relational:Name", "IX_riot_accounts_score");

            var index2 = runtimeEntityType.AddIndex(
                new[] { gameName, tagLine, platformId },
                unique: true);

            var index3 = runtimeEntityType.AddIndex(
                new[] { matchIngestStatus, matchIngestClaimedAtUtc, lastMatchIngestAtUtc });
            index3.AddAnnotation("Relational:Filter", "\"MatchIngestStatus\" <> 0");
            index3.AddAnnotation("Relational:Name", "IX_riot_accounts_ingest_claim_lease");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("PersonaId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType);

            var persona = declaringEntityType.AddNavigation("Persona",
                runtimeForeignKey,
                onDependent: true,
                typeof(Persona),
                propertyInfo: typeof(RiotAccount).GetProperty("Persona", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiotAccount).GetField("<Persona>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var riotAccounts = principalEntityType.AddNavigation("RiotAccounts",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<RiotAccount>),
                propertyInfo: typeof(Persona).GetProperty("RiotAccounts", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Persona).GetField("<RiotAccounts>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "riot_accounts");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
