// <auto-generated />
using System;
using System.Reflection;
using Data.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TimelineLeadSigmaMomentEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Data.Entities.TimelineLeadSigmaMoment",
                typeof(TimelineLeadSigmaMoment),
                baseEntityType,
                propertyCount: 10,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var aggregatedAtUtc = runtimeEntityType.AddProperty(
                "AggregatedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("AggregatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<AggregatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            aggregatedAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var intervalMinute = runtimeEntityType.AddProperty(
                "IntervalMinute",
                typeof(int),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("IntervalMinute", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<IntervalMinute>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            intervalMinute.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var n = runtimeEntityType.AddProperty(
                "N",
                typeof(long),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("N", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<N>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            n.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var patch = runtimeEntityType.AddProperty(
                "Patch",
                typeof(string),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("Patch", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<Patch>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 16);
            patch.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var queueId = runtimeEntityType.AddProperty(
                "QueueId",
                typeof(int),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("QueueId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<QueueId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            queueId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var sumDmg = runtimeEntityType.AddProperty(
                "SumDmg",
                typeof(double),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("SumDmg", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<SumDmg>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            sumDmg.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var sumGold = runtimeEntityType.AddProperty(
                "SumGold",
                typeof(double),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("SumGold", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<SumGold>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            sumGold.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var sumSqDmg = runtimeEntityType.AddProperty(
                "SumSqDmg",
                typeof(double),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("SumSqDmg", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<SumSqDmg>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            sumSqDmg.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var sumSqGold = runtimeEntityType.AddProperty(
                "SumSqGold",
                typeof(double),
                propertyInfo: typeof(TimelineLeadSigmaMoment).GetProperty("SumSqGold", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimelineLeadSigmaMoment).GetField("<SumSqGold>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);
            sumSqGold.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { queueId, patch, intervalMinute },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "timeline_lead_sigma_moments");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
