// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    public partial class TrueMainDbContextModel
    {
        private TrueMainDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("eaaa2f14-97e1-4294-bba2-072eadfbffc8"), entityTypeCount: 27)
        {
        }

        partial void Initialize()
        {
            var championAggregatePattern = ChampionAggregatePatternEntityType.Create(this);
            var championAggregateScope = ChampionAggregateScopeEntityType.Create(this);
            var championDimBuild = ChampionDimBuildEntityType.Create(this);
            var championDimRunePage = ChampionDimRunePageEntityType.Create(this);
            var championDimSkillOrder = ChampionDimSkillOrderEntityType.Create(this);
            var championDimSpellPair = ChampionDimSpellPairEntityType.Create(this);
            var championDimStarterItems = ChampionDimStarterItemsEntityType.Create(this);
            var championMatchupStat = ChampionMatchupStatEntityType.Create(this);
            var championPowerspikeCurveStat = ChampionPowerspikeCurveStatEntityType.Create(this);
            var championPowerspikeEventStat = ChampionPowerspikeEventStatEntityType.Create(this);
            var championTimelineLeadStat = ChampionTimelineLeadStatEntityType.Create(this);
            var discoveryCursor = DiscoveryCursorEntityType.Create(this);
            var jungleFirstClear = JungleFirstClearEntityType.Create(this);
            var mainCandidate = MainCandidateEntityType.Create(this);
            var mainChampionStat = MainChampionStatEntityType.Create(this);
            var match = MatchEntityType.Create(this);
            var matchParticipant = MatchParticipantEntityType.Create(this);
            var matchParticipantKillPosition = MatchParticipantKillPositionEntityType.Create(this);
            var matchParticipantTimelineSnapshot = MatchParticipantTimelineSnapshotEntityType.Create(this);
            var participantPerkSelection = ParticipantPerkSelectionEntityType.Create(this);
            var perkSelectionCatalog = PerkSelectionCatalogEntityType.Create(this);
            var persona = PersonaEntityType.Create(this);
            var powerspikeSigmaStat = PowerspikeSigmaStatEntityType.Create(this);
            var processRun = ProcessRunEntityType.Create(this);
            var rankSnapshot = RankSnapshotEntityType.Create(this);
            var riotAccount = RiotAccountEntityType.Create(this);
            var seedRequest = SeedRequestEntityType.Create(this);

            ChampionAggregatePatternEntityType.CreateForeignKey1(championAggregatePattern, championDimBuild);
            ChampionAggregatePatternEntityType.CreateForeignKey2(championAggregatePattern, championDimRunePage);
            ChampionAggregatePatternEntityType.CreateForeignKey3(championAggregatePattern, championAggregateScope);
            ChampionAggregatePatternEntityType.CreateForeignKey4(championAggregatePattern, championDimSkillOrder);
            ChampionAggregatePatternEntityType.CreateForeignKey5(championAggregatePattern, championDimSpellPair);
            ChampionAggregatePatternEntityType.CreateForeignKey6(championAggregatePattern, championDimStarterItems);
            ChampionAggregateScopeEntityType.CreateForeignKey1(championAggregateScope, riotAccount);
            JungleFirstClearEntityType.CreateForeignKey1(jungleFirstClear, match);
            MatchParticipantEntityType.CreateForeignKey1(matchParticipant, match);
            MatchParticipantEntityType.CreateForeignKey2(matchParticipant, riotAccount);
            MatchParticipantKillPositionEntityType.CreateForeignKey1(matchParticipantKillPosition, match);
            MatchParticipantTimelineSnapshotEntityType.CreateForeignKey1(matchParticipantTimelineSnapshot, match);
            ParticipantPerkSelectionEntityType.CreateForeignKey1(participantPerkSelection, match);
            ParticipantPerkSelectionEntityType.CreateForeignKey2(participantPerkSelection, perkSelectionCatalog);
            RankSnapshotEntityType.CreateForeignKey1(rankSnapshot, riotAccount);
            RiotAccountEntityType.CreateForeignKey1(riotAccount, persona);

            ChampionAggregatePatternEntityType.CreateAnnotations(championAggregatePattern);
            ChampionAggregateScopeEntityType.CreateAnnotations(championAggregateScope);
            ChampionDimBuildEntityType.CreateAnnotations(championDimBuild);
            ChampionDimRunePageEntityType.CreateAnnotations(championDimRunePage);
            ChampionDimSkillOrderEntityType.CreateAnnotations(championDimSkillOrder);
            ChampionDimSpellPairEntityType.CreateAnnotations(championDimSpellPair);
            ChampionDimStarterItemsEntityType.CreateAnnotations(championDimStarterItems);
            ChampionMatchupStatEntityType.CreateAnnotations(championMatchupStat);
            ChampionPowerspikeCurveStatEntityType.CreateAnnotations(championPowerspikeCurveStat);
            ChampionPowerspikeEventStatEntityType.CreateAnnotations(championPowerspikeEventStat);
            ChampionTimelineLeadStatEntityType.CreateAnnotations(championTimelineLeadStat);
            DiscoveryCursorEntityType.CreateAnnotations(discoveryCursor);
            JungleFirstClearEntityType.CreateAnnotations(jungleFirstClear);
            MainCandidateEntityType.CreateAnnotations(mainCandidate);
            MainChampionStatEntityType.CreateAnnotations(mainChampionStat);
            MatchEntityType.CreateAnnotations(match);
            MatchParticipantEntityType.CreateAnnotations(matchParticipant);
            MatchParticipantKillPositionEntityType.CreateAnnotations(matchParticipantKillPosition);
            MatchParticipantTimelineSnapshotEntityType.CreateAnnotations(matchParticipantTimelineSnapshot);
            ParticipantPerkSelectionEntityType.CreateAnnotations(participantPerkSelection);
            PerkSelectionCatalogEntityType.CreateAnnotations(perkSelectionCatalog);
            PersonaEntityType.CreateAnnotations(persona);
            PowerspikeSigmaStatEntityType.CreateAnnotations(powerspikeSigmaStat);
            ProcessRunEntityType.CreateAnnotations(processRun);
            RankSnapshotEntityType.CreateAnnotations(rankSnapshot);
            RiotAccountEntityType.CreateAnnotations(riotAccount);
            SeedRequestEntityType.CreateAnnotations(seedRequest);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
