// <auto-generated />
using Data;
using Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TrueMainDbContext), typeof(TrueMainDbContextModel))]
