// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Data.CompiledModels
{
    public partial class TrueMainDbContextModel
    {
        private TrueMainDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("cecbb13f-70f8-4c22-ad4f-d7f02456eeac"), entityTypeCount: 17)
        {
        }

        partial void Initialize()
        {
            var championAggregatePattern = ChampionAggregatePatternEntityType.Create(this);
            var championAggregateScope = ChampionAggregateScopeEntityType.Create(this);
            var championDimBuild = ChampionDimBuildEntityType.Create(this);
            var championDimRunePage = ChampionDimRunePageEntityType.Create(this);
            var championDimSkillOrder = ChampionDimSkillOrderEntityType.Create(this);
            var championDimSpellPair = ChampionDimSpellPairEntityType.Create(this);
            var championDimStarterItems = ChampionDimStarterItemsEntityType.Create(this);
            var mainCandidate = MainCandidateEntityType.Create(this);
            var mainChampionStat = MainChampionStatEntityType.Create(this);
            var match = MatchEntityType.Create(this);
            var matchParticipant = MatchParticipantEntityType.Create(this);
            var participantPerkSelection = ParticipantPerkSelectionEntityType.Create(this);
            var perkSelectionCatalog = PerkSelectionCatalogEntityType.Create(this);
            var persona = PersonaEntityType.Create(this);
            var processRun = ProcessRunEntityType.Create(this);
            var rankSnapshot = RankSnapshotEntityType.Create(this);
            var riotAccount = RiotAccountEntityType.Create(this);

            ChampionAggregatePatternEntityType.CreateForeignKey1(championAggregatePattern, championDimBuild);
            ChampionAggregatePatternEntityType.CreateForeignKey2(championAggregatePattern, championDimRunePage);
            ChampionAggregatePatternEntityType.CreateForeignKey3(championAggregatePattern, championAggregateScope);
            ChampionAggregatePatternEntityType.CreateForeignKey4(championAggregatePattern, championDimSkillOrder);
            ChampionAggregatePatternEntityType.CreateForeignKey5(championAggregatePattern, championDimSpellPair);
            ChampionAggregatePatternEntityType.CreateForeignKey6(championAggregatePattern, championDimStarterItems);
            ChampionAggregateScopeEntityType.CreateForeignKey1(championAggregateScope, riotAccount);
            MatchParticipantEntityType.CreateForeignKey1(matchParticipant, match);
            MatchParticipantEntityType.CreateForeignKey2(matchParticipant, riotAccount);
            ParticipantPerkSelectionEntityType.CreateForeignKey1(participantPerkSelection, match);
            ParticipantPerkSelectionEntityType.CreateForeignKey2(participantPerkSelection, perkSelectionCatalog);
            RankSnapshotEntityType.CreateForeignKey1(rankSnapshot, riotAccount);
            RiotAccountEntityType.CreateForeignKey1(riotAccount, persona);

            ChampionAggregatePatternEntityType.CreateAnnotations(championAggregatePattern);
            ChampionAggregateScopeEntityType.CreateAnnotations(championAggregateScope);
            ChampionDimBuildEntityType.CreateAnnotations(championDimBuild);
            ChampionDimRunePageEntityType.CreateAnnotations(championDimRunePage);
            ChampionDimSkillOrderEntityType.CreateAnnotations(championDimSkillOrder);
            ChampionDimSpellPairEntityType.CreateAnnotations(championDimSpellPair);
            ChampionDimStarterItemsEntityType.CreateAnnotations(championDimStarterItems);
            MainCandidateEntityType.CreateAnnotations(mainCandidate);
            MainChampionStatEntityType.CreateAnnotations(mainChampionStat);
            MatchEntityType.CreateAnnotations(match);
            MatchParticipantEntityType.CreateAnnotations(matchParticipant);
            ParticipantPerkSelectionEntityType.CreateAnnotations(participantPerkSelection);
            PerkSelectionCatalogEntityType.CreateAnnotations(perkSelectionCatalog);
            PersonaEntityType.CreateAnnotations(persona);
            ProcessRunEntityType.CreateAnnotations(processRun);
            RankSnapshotEntityType.CreateAnnotations(rankSnapshot);
            RiotAccountEntityType.CreateAnnotations(riotAccount);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
