using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Data.Configurations;

/// <summary>
/// Maps Postgres' system <c>xmin</c> column as a whole-row optimistic concurrency
/// token. Npgsql's <c>UseXminAsConcurrencyToken()</c> helper was removed in
/// Npgsql.EntityFrameworkCore.PostgreSQL 10, so this reproduces exactly what it
/// used to configure: a shadow <c>uint</c> property bound to the <c>xmin</c>
/// system column (type <c>xid</c>), value-generated by the database on every
/// insert/update and used as a concurrency token. <c>xmin</c> is a system column,
/// so this carries no physical schema change — only a model-level shadow property.
/// </summary>
internal static class XminConcurrencyExtensions
{
    public static EntityTypeBuilder<TEntity> UseXminAsConcurrencyToken<TEntity>(
        this EntityTypeBuilder<TEntity> entity)
        where TEntity : class
    {
        entity.Property<uint>("xmin")
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        return entity;
    }
}
