FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /workspace

COPY ["Directory.Build.props", "./"]
COPY ["Api/Api.csproj", "Api/"]
COPY ["Core/Core.csproj", "Core/"]
COPY ["Data/Data.csproj", "Data/"]
RUN dotnet restore "Api/Api.csproj"

COPY ["Api/", "Api/"]
COPY ["Core/", "Core/"]
COPY ["Data/", "Data/"]

EXPOSE 8080

CMD ["dotnet", "watch", "--project", "Api/Api.csproj", "run", "--no-launch-profile"]
